# Generated by Django 5.2.13 on 2026-05-11 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, verbose_name='Nomor Kendaraan')),
                ('driver_name', models.CharField(max_length=100, verbose_name='Nama Driver')),
                ('origin_name', models.CharField(max_length=100, verbose_name='Titik Keberangkatan')),
                ('destination_name', models.CharField(max_length=100, verbose_name='Titik Tujuan')),
                ('destination_lat', models.FloatField(verbose_name='Latitude Tujuan')),
                ('destination_lng', models.FloatField(verbose_name='Longitude Tujuan')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Terjadwal'), ('ON_GOING', 'Dalam Perjalanan'), ('COMPLETED', 'Selesai')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shuttlelocation',
            name='trip_id',
        ),
        migrations.AddField(
            model_name='shuttlelocation',
            name='trip_id_old',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shuttlelocation',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tracking.trip'),
        ),
    ]
