# Generated by Django 5.2.13 on 2026-05-11 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_trip_remove_shuttlelocation_trip_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Plat Nomor')),
                ('model_name', models.CharField(max_length=50, verbose_name='Model Kendaraan')),
                ('capacity', models.IntegerField(default=10, verbose_name='Kapasitas Kursi')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Keberangkatan'),
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='tracking.vehicle'),
        ),
    ]
