# Generated by Django 5.2.13 on 2026-05-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_vehicle_trip_departure_time_trip_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='origin_lat',
            field=models.FloatField(default=-6.3071, verbose_name='Latitude Asal'),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin_lng',
            field=models.FloatField(default=107.2947, verbose_name='Longitude Asal'),
        ),
    ]
