# Generated by Django 5.2.13 on 2026-05-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_trip_origin_lat_trip_origin_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nama Terminal/Halte')),
                ('city', models.CharField(max_length=100, verbose_name='Kota')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('address', models.TextField(verbose_name='Alamat Lengkap')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
